### ISSUE TITLE
Playmode doesn't change from before kickoff in run or kick challenges so challenges never start

### ISSUE THREAD

**Issue by pmacalpine** [klausdorer/magmaChallenge#7] opened 2016-05-11 22:51 UTC
When starting the run challenge or kick challenge the agent never shows up.  This is using startMagmaChallenge.sh as the name of the start script.  Both the run and kick challenge do still work in version 2.3 which had to be used at this year's IranOpen where a run challenge took place.  Maybe something was broken in the run and kick challenges between versions 2.3 and 2.4?

**Comment by Gama11** [comment] 2016-05-12 10:07
I think the script name has to be `startChallengePlayer.sh`, not `startMagmaChallenge.sh`.

**Comment by pmacalpine** [comment] 2016-05-12 15:06
You're right about the script name needing to be startChallengePlayer.sh.  While this is mentioned in the README, I think it's a bit counter-intuitive that you select a start script with the file chooser and then a different named start script in the same directory is expected to run.  That's another whole design issue however...

When I first noticed a problem with the run challenge back when the IranOpen was happening it wasn't that agents weren't starting (assuming you got the start script name right), it was that the playmode never switched from Before_KickOff so the challenge never actually started and eventually just timed out.  This is happening for both the run and kick challenges which do work in version 2.3 of the framework.  The keepaway challenge does start for me correctly however.

**Comment by Gama11** [comment] 2016-05-12 15:13
I agree. I didn't notice this during testing because I usually enter the path directly into the table instead of going through the file dialog. I've been wanting to replace it with a folder chooser dialog and add a check that makes sure the selected folder contains a file named `startChallengePlayer.sh`.

I'll look into the run / kick challenge.

**Comment by Gama11** [comment] 2016-05-14 11:13
I can reproduce this issue.

**Comment by Gama11** [comment] 2016-05-15 12:29
Should be fixed now. Thanks for reporting!

**Closed as completed** 2016-05-15 12:28 UTC
Labels: bug
